// default 
package com.charity.events.bean;
// Generated 14/07/2015 10:56:53 AM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * EventInfo generated by hbm2java
 */
@Entity
@Table(name = "event_info")
public class EventInfo implements java.io.Serializable {

	private String id;
	private String memberId;
	private Date attendDate;
	private Integer donate;

	public EventInfo() {
	}

	public EventInfo(String id, String memberId) {
		this.id = id;
		this.memberId = memberId;
	}

	public EventInfo(String id, String memberId, Date attendDate, Integer donate) {
		this.id = id;
		this.memberId = memberId;
		this.attendDate = attendDate;
		this.donate = donate;
	}

	@Id
	@GeneratedValue(generator = "uuid")
	@GenericGenerator(name = "uuid", strategy = "uuid")
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "member_id", nullable = false, length = 32)
	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "attend_date", length = 19)
	@JsonFormat(pattern="yyyy-MM-dd")
	public Date getAttendDate() {
		return this.attendDate;
	}

	public void setAttendDate(Date attendDate) {
		this.attendDate = attendDate;
	}

	@Column(name = "donate")
	public Integer getDonate() {
		return this.donate;
	}

	public void setDonate(Integer donate) {
		this.donate = donate;
	}

}
